### ISSUE TITLE
題材になっているKaggleのデータセットのURLにアクセスできない。

### ISSUE THREAD

**Issue by flower-pepper** [gunosy/Gunosy-Internship-Textbook#6]
クレジットカードの不正検出のデータセットのURL
https://www.kaggle.com/dalpozz/creditcardfraud
にアクセスしようとすると、
404 We can't find that page.
というメッセージが表示される。
(確認環境 : Ubuntu 18.04.1 LTS, Firefox Quantum 61.0.1)

以下のURLが現在アクセス可能で、同じデータセットのものと思われる。
https://www.kaggle.com/mlg-ulb/creditcardfraud/version/2

**Comment by takaiyuk** [comment]
https://github.com/gunosy/Gunosy-Internship-Textbook/pull/7 でデータセットの URL を https://www.kaggle.com/mlg-ulb/creditcardfraud に変更した。
